version: '3.8'

services:
  admin-cesca:
    image: admin-cesca:latest
    networks:
      - network_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        # Enable Traefik for this service
        - "traefik.enable=true"

        # HTTP Router
        - "traefik.http.routers.admin-cesca.rule=Host(`admin.cesca.digital`)"
        - "traefik.http.routers.admin-cesca.entrypoints=web"
        - "traefik.http.routers.admin-cesca.middlewares=admin-cesca-redirect@docker"

        # HTTPS Router
        - "traefik.http.routers.admin-cesca-secure.rule=Host(`admin.cesca.digital`)"
        - "traefik.http.routers.admin-cesca-secure.entrypoints=websecure"
        - "traefik.http.routers.admin-cesca-secure.tls=true"
        - "traefik.http.routers.admin-cesca-secure.tls.certresolver=letsencryptresolver"

        # Middleware: HTTP to HTTPS redirect
        - "traefik.http.middlewares.admin-cesca-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.admin-cesca-redirect.redirectscheme.permanent=true"

        # Service (specify port)
        - "traefik.http.services.admin-cesca.loadbalancer.server.port=80"

networks:
  network_public:
    external: true
